### ISSUE TITLE
Couple of small fixes

### ISSUE THREAD

**Issue by llcawthorne** [micronaut-guides/micronaut-security-session#4]
I can't find common-geb.adoc to edit it myself and make a pull request, but when you give an example of what to put in GebConfig, you might want to specifically say it goes into a file in `src/test/resources` named `GebConfig.groovy`.  Most other places you give filenames.  

Also, the document leaves the imports off SessionAuthenticationSpec.  I had to add the following imports:

```
import example.micronaut.HomePage
import example.micronaut.LoginPage
import geb.spock.GebSpec
import io.micronaut.context.ApplicationContext
import io.micronaut.runtime.server.EmbeddedServer
import spock.lang.AutoCleanup
import spock.lang.Share
```

Also, you refer to a page named LoginFailedPage in SessionAuthenticationSpec that you didn't have us create.  I think you just meant to refer to LoginPage (since LoginFailedPage is the same page, just with errors displayed).

**Comment by ilopmar** [comment]
The "common" files for all guides are in this repo https://github.com/micronaut-projects/micronaut-guides/tree/master/src/main/docs
Please submit the PR there.

Thanks!

**Comment by ilopmar** [comment]
- I've added the path to `GebConfig.groovy` file to the common snippet.
- We left out the imports in the guide but you can check the source code directly to see all of them. 
- I've added `LoginFailedPage` to the guide.
